---
title: "Getting and Cleaning Data - Peer Assignment"
author: "dumsim"
date: "Saturday, April 25, 2015"
output: html_document
---
### Purpose
To demonstrate working with and cleaning a data set.

### Goal
Prepare tidy data from a Samsung Galaxy S smartphone accelerometer source data set.  

### Source data
The source data, source data codebook and readme can be foujnd at:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip   

######*Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012*  

### Ojective
Utilizing the source data, create a single set of tidy data that presents, by category **Subject** by sub-category **Activity**, the average of each source data variables that contains means or standard deviations.

### Approach
1. Save source data to the working directory
2. Load source variable data from the working directory into a range of temporary data tables (the data is provided in 2 discrete sets, named 'Test'and 'Train', and across 3 data tables named 'Subject', 'Activity' and 'Features')
3. Load source variable data labels from the working directory into a range of temporary data table variables  
4. Check that the Test and Train datasets share the same column dimension and that the Subject, Activity and Features tables contain the same number of rows.
5. Combine Test and Train data-sets for Subject, Activity and Features tables into temporary data frames
6. Merge activity labels into activity data
7. Apply labels to combined data frame columns  
8. Reduce data frame features to source data variables containing means or standard deviations using pattern matching on "mean(" or "std("
  d_activity<-merge(d_activity,labels_activity)
9. Merge Subject, Activity and Features tables into data table
10. Clean column names to remove special characters and improve usability in R  
11. Summarize by Subject by Activity, the average of each feature column in the data table and write to 'SamsungOutput.txt'       
12. Remove temporary files

### Project Content

- 'readme.html'
- 'CodeBook.html': Shows information about the variables used from the source data
- 'run_analysis.R': The R-script used to transform the source data set to the tidy data set
- 'LICENSE': The MIT License and Copyright
